Endpoint Fixes
indieweb/wordpress-indieauth pull request #35
Opened 2018-04-06 23:37 UTC by dshanske

This tries to address the Error Logging issue by adding a conversion back to WP_Error in the Oauth Error Response function and adds checks to convert back.

It also changes the settings options to show radio buttons for custom, built-in, or Indieauth.com.

The login form to login with your domain is no longer shared with the regular login form and is accessed at wp-login.php?action=indielogin . There is a setting to show a link to it on the regular login form.

2018-04-07 13:50 UTC, dshanske commented
@pfefferle Hope this resolves your issue.

2018-04-08 18:46 UTC, pfefferle commented
Cool, now the error reporting works, but I still can't login!

```Invalid authorization code```

2018-04-08 18:59 UTC, pfefferle commented
@aaronpk @dshanske as far as I understand OAuth and IndieAuth, you have to get and verify the tokens from the URL you want to login with... This code seems to use the endpoint from the URL I want to be logged in... https://github.com/indieweb/wordpress-indieauth/blob/master/includes/class-indieauth-authenticate.php#L177

Am I wrong?

2018-04-08 19:01 UTC, pfefferle commented
same here: https://github.com/indieweb/wordpress-indieauth/blob/master/includes/class-indieauth-authenticate.php#L95

2018-04-08 19:01 UTC, dshanske commented
That's my fault. The verify code was written when I was upgrading the original function, and I must not have upgraded it. Will address.

2018-04-08 19:16 UTC, dshanske commented
Reading this more closely. verify_access_token does not get called except when logging into the site. Since, at the moment, whatever is in the option is what will be in the header, changing that to discover the endpoint won't work.

2018-04-08 19:33 UTC, aaronpk commented on templates/indieauth-login-form.php
> +	add_action( 'indieauth_login_form' );
this is missing a second parameter:

> Fatal error: Uncaught ArgumentCountError: Too few arguments to function add_action(), 1 passed

2018-04-08 19:55 UTC, pfefferle requested changes

2018-04-08 19:55 UTC, pfefferle commented on includes/class-indieauth-authenticate.php
> +			$endpoint = get_option( 'indieauth_token_endpoint', rest_url( 'indieauth/1.0/token' ) );
this fallback does not work, you never want to use the local endpoint to verify!

2018-04-08 19:55 UTC, pfefferle commented on includes/class-indieauth-authenticate.php
> +			$endpoint = get_option( 'indieauth_authorization_endpoint' );
same as above, the local endpoint should never be used!

2018-04-08 19:55 UTC, pfefferle commented on includes/class-indieauth-authenticate.php
> +	public function verify_access_token( $token, $endpoint = null ) {
where is it `$endpoint` set?

2018-04-08 19:56 UTC, dshanske commented on includes/class-indieauth-authenticate.php
> +	public function verify_access_token( $token, $endpoint = null ) {
Working on that now.

2018-04-08 20:57 UTC, pfefferle approved these changes

2018-04-08 20:57 UTC, pfefferle commented on templates/indieauth-login-form.php
> +	add_action( 'indieauth_login_form' );
fixed

2018-04-08 23:22 UTC, merged